:wrench: Onboard a user
MyParcelCOM/api-specification pull request #1020
Opened 2024-04-08 10:42 UTC by zwaans

# Changes
introduced onboard endpoint

## Todo: 
- [ ] What do we protect this with?

2024-04-08 11:34 UTC, zwaans commented on specification/paths/Onboarding-v1-invitations-invitation_id-onboard.json
> +                  "address": {
How can we make certain fields in the `address` required?

2024-04-11 09:52 UTC, M4tini requested changes

2024-04-11 09:52 UTC, M4tini commented on specification/paths/Onboarding-v1-invitations-invitation_id-onboard.json
> +                  },
You can make `address` fields required by defining a second object it needs to adhere to.
Same goes for the `return_address` fields.
```suggestion
                  "address": {
                    "allOf": [
                      {
                        "$ref": "#/components/schemas/BaseAddress"
                      },
                      {
                        "required": [
                          "street_1",
                          "city",
                          "country_code"
                        ]
                      },
                    ]
                  },
```

2024-04-12 14:22 UTC, M4tini requested changes

2024-04-12 14:22 UTC, M4tini commented on specification/paths/Onboarding-v1-invitations-invitation_id-onboard.json
> +      "RPC"
```suggestion
      "Invitations"
```

2024-04-12 14:22 UTC, M4tini commented on specification/paths/Onboarding-v1-invitations-invitation_id-onboard.json
> +    "description": "This endpoint creates a user based on an invitation.",
```suggestion
    "description": "This `RPC` endpoint creates a user based on an invitation.",
```

2024-04-12 14:22 UTC, M4tini commented on specification/paths/Onboarding-v1-invitations-invitation_id-onboard.json
> +        "application/vnd.api+json": {
```suggestion
        "application/json": {
```

2024-04-12 14:36 UTC, M4tini approved these changes

2024-04-12 14:36 UTC, merged