✨  package_type added to order response and return response
MyParcelCOM/api-specification pull request #1052
Opened 2024-06-27 15:23 UTC by yoan-myparcel

2024-06-28 10:32 UTC, M4tini submitted a review, later dismissed

2024-07-02 14:24 UTC, NickVries requested changes

2024-07-02 14:57 UTC, yoan-myparcel commented on specification/schemas/returns/ReturnResponse.json
> +          ],
Done!

2024-07-03 07:25 UTC, NickVries approved these changes

2024-07-03 12:06 UTC, merged