✨ Add volumetric_weight_divisor_factor to Contract resource
MyParcelCOM/api-specification pull request #1073
Opened 2024-08-02 07:32 UTC by M4tini

https://myparcelcombv.atlassian.net/browse/MP-6757
---
Added `volumetric_weight_divisor_factor` to the `Contract` resource.

2024-08-02 09:23 UTC, M4tini commented on specification/schemas/contracts/Contract.json
> +              "type": "integer",
This needs to be a float or number

2024-08-02 12:28 UTC, NickVries requested changes

2024-08-02 12:28 UTC, NickVries commented on specification/schemas/contracts/Contract.json
> +            },
Perhaps a short description could be useful here.

2024-08-05 07:51 UTC, NickVries approved these changes

2024-08-05 07:51 UTC, merged