✨ Introduced PUDO features
MyParcelCOM/api-specification pull request #718
Opened 2022-07-04 14:00 UTC by yoan-myparcel

# Changes
Added also the first feature "print-label-in-store"

2022-07-04 14:43 UTC, M4tini requested changes

2022-07-04 14:43 UTC, M4tini commented on specification/paths/Carriers-carrier_id-PickupDropoffLocations-latitude-longitude.json
> +        "description": "Comma separated list of features to return. Possible options are:<ul><li>`print-label-in-store`</li></ul>",
```suggestion
        "description": "Comma separated list of features to filter the locations by. Possible options are:<ul><li>`print-label-in-store`</li></ul>",
```

2022-07-05 14:31 UTC, yoan-myparcel commented
@M4tini applied suggestions!

2022-07-05 22:10 UTC, M4tini approved these changes

2022-07-05 22:10 UTC, merged