:wrench: update export-rates-template spec to new format: request-rates-template and download-rates-template
MyParcelCOM/api-specification pull request #886
Opened 2023-09-04 10:59 UTC by yoerriwalstra

Related Jira Issue: https://myparcelcombv.atlassian.net/browse/MP-5988

2023-09-05 08:36 UTC, NickVries requested changes
One more thing, I think it'd be good to have some kind of information on either of the endpoints (I'm currently not sure which one it is) to indicate how to check the progress of the file download. It's returned by one of the endpoints, right?

2023-09-05 08:36 UTC, NickVries commented on specification/paths/RequestRatesTemplate.json
> +    "description": "This endpoint queues a job to create a rates template (CSV) based on existing service rates. The template can be downloaded on completion.",
```suggestion
    "description": "This endpoint queues a job to create a rates template (CSV) based on existing service rates. The template can be downloaded on completion using the `/download-rates-template` endpoint.",
```

2023-09-05 09:15 UTC, yoerriwalstra commented on specification/paths/DownloadRatesTemplate.json
> +      "description": "The object containing a request id.",
done

2023-09-05 09:15 UTC, yoerriwalstra commented on specification/paths/RequestRatesTemplate.json
> +    "description": "This endpoint queues a job to create a rates template (CSV) based on existing service rates. The template can be downloaded on completion.",
done

2023-09-06 07:59 UTC, M4tini approved these changes

2023-09-06 07:59 UTC, merged