👌🏻  Added missing image_url for most returned item analytics
MyParcelCOM/api-specification pull request #997
Opened 2024-02-07 15:04 UTC by yoan-myparcel

2024-02-07 16:50 UTC, M4tini requested changes

2024-02-07 16:50 UTC, M4tini commented on specification/schemas/returns/MostReturnedItem.json
> +        "image_url",
This cannot be required, since it's optional for our Return resource items.
```suggestion
```

2024-02-07 16:54 UTC, M4tini commented on specification/schemas/returns/MostReturnedItem.json
> +        "image_url",
I see that the API is going to [default to a confetti SVG](https://github.com/MyParcelCOM/api/pull/3182/files#diff-36283a1efa4f84c3a5afdbab4f0006cbca5d8af147318fee511dbf1bd042b812R19) but placeholders are a responsibility of the front-end.

2024-02-08 10:21 UTC, M4tini approved these changes

2024-02-08 11:10 UTC, NickVries approved these changes

2024-02-08 11:10 UTC, merged